kubernetes-sigs/e2e-framework

pkg/conf/config_test.go

/kind bug
There is a misspelling of function name. This patch fixes it.
Fixes #11

Fixed typo error in function name

---

klient/conf/config.go
klient/conf/config_test.go
klient/conf/main_test.go

Initial implementation of rest.Config constructor functions which helps to get the client connection with the api-server.

initial commit for klient helper package

---

klient/k8s/resources/main_test.go
klient/k8s/resources/resources.go
klient/k8s/resources/resources_test.go

This PR renames Res method under klient/k8s to Resource.
This was suggested by @andrewsykim as part of review comments [here](https://github.com/kubernetes-sigs/e2e-framework/pull/26#discussion_r664695191)
/cc @ShwethaKumbla

Rename Res method to Resource

---

examples/k8s/main_test.go
pkg/envconf/config.go

Add a envconfig.Config method to inject a client from kubeconfig file

---

pkg/env/action.go
pkg/env/env.go
pkg/env/env_test.go
pkg/features/builder.go
pkg/internal/types/types.go

- Removed the FeatureInfo type in favor of the Feature interface
- Added logic to make a deep copy rather than pass the feature itself
- Added a test to confirm we dont allow mutation of the feature in
the before/after hooks
Fixes #69 
Signed-off-by: John Schnake <jschnake@vmware.com>

Rework the FeatureInfo wiring

---

support/kind/kind.go

When running kind with podman, an extra log appears that is getting picked up by the `support/kind` package and breaking:
Example:
```bash
kind v0.11.1 go1.16.4 linux/amd64
enabling experimental podman provider
myclustername1
```
https://github.com/kubernetes-sigs/kind/blob/fa7d86470f4c0e924fc4c2e767ec8491c45f4304/pkg/cluster/internal/providers/podman/provider.go#L45
This is output when running `kind get kubeconfig` to stderr -- the current processes combine stdout + stderr and results in an invalid yaml file.
This change writes only the stdout contents to the kubeconfig file. An alternative might be to run `kind get kubeconfig` with the `-q` flag.

use stdout from kind command when writing kubeconfig

---

pkg/envfuncs/kind_funcs.go
support/kind/kind.go

Support loading docker images from the host to the kind cluster:
-  `kind load docker-image --name ${cluster} ${dockerImage}`
-  `kind load image-archive --name ${cluster} ${dockerImage}`
https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

support loading images into kind cluster

---

examples/wait_for_resources/README.md
examples/wait_for_resources/main_test.go
examples/wait_for_resources/wait_test.go
klient/internal/testutil/setup.go
klient/wait/conditions/conditions.go
klient/wait/wait_test.go
pkg/envfuncs/kind_funcs.go

While reviewing the conditions package I noticed there weren't any functions to help deal with lists of objects nor helpers built around `k8s.Object` to deal with types outside of pod, jobs, and other core types.
I think I should be able to use any type in my codebase now.
Saw #78 --  so I tried to add some examples as well.

add condition helpers and examples

---

docs/design/resource-decoding.md
examples/decoder/README.md
examples/decoder/decoder_test.go
examples/decoder/main_test.go
examples/decoder/testdata/configmap.yaml
examples/decoder/testdata/deployment.yaml
examples/decoder/testdata/service.json
klient/decoder/decoder.go
klient/decoder/decoder_test.go
klient/decoder/main_test.go
klient/decoder/testdata/example-configmap-1.yaml
klient/decoder/testdata/example-configmap-3.json
klient/decoder/testdata/example-multidoc-1.yaml
klient/decoder/testdata/examples/example-configmap-2.yaml
klient/decoder/testdata/examples/example-sa-1.yaml
klient/decoder/testdata/examples/example-sa-2.yml
klient/decoder/testdata/examples/example-sa-3.json
klient/decoder/testdata/fake-crd.yaml

This was created to solve for #43 based on some common patterns from my kubebuilder codebase that I am adapting to this framework.
After I started to write the tests and validate JSON functionality, the naming of the package and the functions became outdated.
Should this functionality move inside one of the existing packages -- e.g. `resources`?

add yaml and json helpers

---

pkg/env/action.go
pkg/env/env.go
pkg/env/env_test.go
pkg/internal/types/types.go

In order to get test pass/fail information in these hooks
we need access to the testing object.
Fixes #101 
** NOTE **
I wanted to add a test for this but the problem is that it passes the testing.T object around so even when we get the expected behavior, when we fail the test and confirm it cascades, there is no way to avoid `go test` from still counting that as a failure.
The workaround for this would be to make a mock that implements `testing.TB` and use that, but our signatures everywhere use *testing.T explicitly so that wont work.
Manually confirmed it did cascade though.
Signed-off-by: John Schnake <jschnake@vmware.com>

Add *testing.T to before/after feature hooks

---

OWNERS

I haven't had time to be suitably active in this repo like I should be as a reviewer / approver.

emeritus bentheelder

---

pkg/env/env.go
support/kind/kind.go

Closes #119 
```bash
❯ go test -v . -args --parallel
I0316 19:26:00.910966   58073 parallel_features_test.go:46] "Args" flag=&{client:<nil> kubeconfig: namespace: assessmentRegex:<nil> featureRegex:<nil> labels:map[] skipFeatureRegex:<nil> skipLabels:map[] skipAssessmentRegex:<nil> parallelTests:true}
=== RUN   TestPodBringUp
=== RUN   TestPodBringUp/Feature_Two
=== RUN   TestPodBringUp/Feature_Two/Create_Nginx_Deployment_2
=== RUN   TestPodBringUp/Feature_One
=== RUN   TestPodBringUp/Feature_One/Create_Nginx_Deployment_1
=== RUN   TestPodBringUp/Feature_Two/Wait_for_Nginx_Deployment_2_to_be_scaled_up
=== RUN   TestPodBringUp/Feature_One/Wait_for_Nginx_Deployment_1_to_be_scaled_up
--- PASS: TestPodBringUp (65.08s)
--- PASS: TestPodBringUp/Feature_Two (65.05s)
--- PASS: …
```

GIT-119: handle scoping for parallel tests

---

docs/design/fail-fast-mode.md
examples/fail_fast/README.md
pkg/env/env.go
pkg/envconf/config.go
pkg/envconf/config_test.go
pkg/flags/flags.go

Closes #112 
```bash
❯ ./example.test -test.v
=== RUN   TestExample
=== RUN   TestExample/fail-feature
=== RUN   TestExample/fail-feature/1==2
example_test.go:15: 1 != 2
=== RUN   TestExample/fail-feature/print
example_test.go:23: THIS LINE SHOULDN'T BE PRINTED
=== RUN   TestExample/next-feature
=== RUN   TestExample/next-feature/print
example_test.go:30: THIS LINE ALSO SHOULDN'T BE PRINTED
--- FAIL: TestExample (0.00s)
--- FAIL: TestExample/fail-feature (0.00s)
--- FAIL: TestExample/fail-feature/1==2 (0.00s)
--- PASS: TestExample/fail-feature/print (0.00s)
--- PASS: TestExample/next-feature (0.00s)
--- PASS: TestExample/next-feature/print (0.00s)
=== RUN   TestNext
=== RUN   TestNext/next-test-feature
=== RUN   TestNext/next-test-feature/print
example_test.go:42: THIS LINE SHOULD BE …
```

GIT-112: enable framework specific fail-fast mode

---

examples/crds/README.md
examples/crds/envtest_test.go
examples/crds/main_test.go
examples/crds/testdata/crds/stable.example.com.crontabs.yaml
examples/crds/testdata/crontabs/register.go
examples/crds/testdata/crontabs/type.go
examples/crds/testdata/crs/sample.yaml
klient/decoder/decoder.go
pkg/envfuncs/resource_funcs.go

Closes #109 
cc @crandles  Hope this address the ask you have had in the Issue you opened. 
```bash
=== RUN   TestCRDSetup
=== RUN   TestCRDSetup/Custom_Controller
=== RUN   TestCRDSetup/Custom_Controller/Check_If_Resource_created
I0502 19:36:18.886351   72899 envtest_test.go:60] "CR Details" cr=&{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:my-new-cron-object GenerateName: Namespace:my-ns-6dde SelfLink: UID:6769a909-6188-40a5-bc28-6e50df6a561b ResourceVersion:546 Generation:1 CreationTimestamp:2022-05-02 19:36:18 +0530 IST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[{Manager:envtest.test Operation:Update APIVersion:stable.example.com/v1 Time:2022-05-02 19:36:18 +0530 IST …
```

GIT-109: enable CRD setup helper to ease the testing of Operators

---

README.md

Fix compiling errors in test function example from readme.
* nspaces should be `corev1.NamespaceList` type
* testenv.Test signature is `Test(*testing.T, ...Feature)`, so t should be first arg

docs(readme): fix test example

---

examples/wait_for_resources/README.md

Consistently use tabs to indent, so the code examples are rendered with
consistent indentation.

examples/wait_for_resources: fix Go code indentation in README

---

README.md
examples/multi_cluster/README.md
examples/multi_cluster/deployment_test.go
examples/multi_cluster/main_test.go
examples/multi_cluster/testdata/example_chart/.helmignore
examples/multi_cluster/testdata/example_chart/Chart.yaml
examples/multi_cluster/testdata/example_chart/templates/deployment.yaml
examples/multi_cluster/testdata/example_chart/templates/service.yaml
examples/multi_cluster/testdata/example_chart/templates/tests/test-connection.yaml
examples/multi_cluster/testdata/example_chart/values.yaml
pkg/envfuncs/kind_funcs.go

Closes #138 
1. Add an example of how to perform multi cluster test.
2. Minor adjustment to the `envfuncs` to be able to extract the kind cluster from `ctx` 
Closes #130  as well

multi-cluster workflow: add example of multi cluster test workflow

---

klient/conf/main_test.go
support/kind/kind.go

Replacing usages of `io/ioutil` with its recommendations should fix https://github.com/kubernetes-sigs/e2e-framework/issues/159 .
I hope this is in your interest 😃

build: fix golangci-lint SA1019 io/ioutil

---

pkg/env/action.go
pkg/env/action_test.go
pkg/env/env.go

Hi
This change should fix https://github.com/kubernetes-sigs/e2e-framework/issues/161 by logging the correct action role as prefix when failing during a test lifecycle action.
Thanks for having a look in advance & keep up the good work!

Fix log output on errors during test lifecycle actions

---

klient/client.go
klient/k8s/resources/resources.go

Enable the ability to fetch the reusable controller-runtime client via the `e2e-framework` infra. 
https://github.com/kubernetes-sigs/e2e-framework/issues/146#issuecomment-1177699723 Has a good explanation on the usability of this features. 
Fixes #146

controller-runtime: enable ability to fetch controller runtime client

---

pkg/env/env.go
third_party/kubetest2/README.md
third_party/kubetest2/cmd/kubetest2-tester-e2e-framework/main.go
third_party/kubetest2/go.mod
third_party/kubetest2/go.sum
third_party/kubetest2/pkg/tester/e2e-tester.go
third_party/kubetest2/pkg/tester/e2e-tester_test.go

This PR implements a kubetest2 tester to run e2e-framework tests can be executed with kubetest2 as:
```bash
$> kubetest2 kind --up --down        \
--test=e2e-framework --         \
--packages ./cluster            \
--kubeconfig=$HOME/.kube/config \
--skip-assessments=pod-count
```
See README.md for doc.
Closes #132 
Closes #174

Support for an e2e-framework kubetest2 tester

---

pkg/env/env.go
pkg/env/env_test.go
pkg/envconf/config.go
pkg/features/builder.go
pkg/features/builder_test.go
pkg/flags/flags.go
pkg/flags/flags_test.go
pkg/internal/types/types.go

Changes `--labels` and `--skip-labels` parsing logic to allow for multiple values for the same label `key`.
Fixes: #194

fix: Parse multiple label values for same key

---

examples/flags/README.md
klient/conf/config.go
klient/conf/main_test.go
pkg/envconf/config.go
pkg/flags/flags.go

Fix https://github.com/kubernetes-sigs/e2e-framework/issues/187
@vladimirvivien I know this is not what you suggested, but I spent some time looking at the cli-runtime and couldn't figure out how to wire it.
Since this is blocking our adoption and it is a pretty simple change, I'd like to ask you if we can still merge it and then I can try to take again a look at the cli-runtime fix

Add --context flag

---

examples/skip_flags/README.md

Fixes https://github.com/kubernetes-sigs/e2e-framework/issues/200
Go 1.20 introduces the ```-skip``` flag for ```go test``` command to skip tests.
Document how to use this flag in examples/skip_flags

Document -skip flag in go test

---

.golangci.yml
go.mod
hack/verify-golangci-lint.sh
klient/decoder/decoder.go

need job update: https://github.com/kubernetes/test-infra/pull/29088
/assign @vladimirvivien

Update go.mod to be min 1.19 and golangci-lint

---

README.md
examples/third_party_integration/helm/helm_test.go

Fixes: https://github.com/kubernetes-sigs/e2e-framework/issues/228
/assign @vladimirvivien @ShwethaKumbla @harshanarayana

update helm test

---

.github/dependabot.yml
.github/workflows/release.yml

- Updates for dependabot and ci job
/assign @vladimirvivien

Updates for dependabot and ci job

---

examples/third_party_integration/helm/helm_test.go

Follow up of https://github.com/kubernetes-sigs/e2e-framework/pull/229/files#r1155138390
but instead, publish our own lets pin to a specific version that is working
will be too much work and does worth publishing a test one for testing IMHO
/assign @vladimirvivien @harshanarayana

pin helm chart to a specific version

---

examples/skip_flags/README.md
examples/skip_flags/k8s_test.go
pkg/env/env.go

Follow-up on #194 where the logic was still not correct in all cases. The behavior is now as expected: if `--labels` is specified all keys and values specified must match a feature. This allows for arbitrary and complex combinations of multiple features within one suite.
For example:
```go
f1 := features.New("label demo 1").
WithLabel("a", "1").
WithLabel("all", "true").
Feature()
f2 := features.New("label demo 2").
WithLabel("all", "true").
Feature()
f3 := features.New("label demo 3").
WithLabel("a", "2").
WithLabel("all", "true").
Feature()
f4 := features.New("label demo 4").
WithLabel("a", "1").
WithLabel("b", "1").
WithLabel("all", "true").
Feature()
```
Leads to the following outcomes with different `--labels`:
```console
go test -race -v ./e2e -args -v 4 --labels=some=value
--- …
```

fix: Label handling

---

examples/every_test_custom_ns/README.md
examples/every_test_custom_ns/k8s_test.go
examples/every_test_custom_ns/main_test.go

The current example doesn't tell us how to use the namespace after we pass it to the context. This PR fixes it with a working example, while addressing a couple of go static-check fixes.
Tested with
```
❯ go test -v ./...
=== RUN   TestListPods
main_test.go:91: Creating NS ns-d-903b2 for test TestListPods
=== RUN   TestListPods/pod_list
=== RUN   TestListPods/pod_list/pods_from_namespace
k8s_test.go:37: found 0 pods in namespace ns-d-903b2
=== NAME  TestListPods
main_test.go:100: Deleting NS ns-d-903b2 for test TestListPods
--- PASS: TestListPods (0.07s)
--- PASS: TestListPods/pod_list (0.00s)
--- PASS: TestListPods/pod_list/pods_from_namespace (0.00s)
PASS
ok  	sigs.k8s.io/e2e-framework/examples/every_test_custom_ns	31.204s
```

Fix every_test_custom_ns test example

---

support/kind/kind.go

This commit improves the understandability of errors occuring upon loading images and image archives (and others as fly-by) by providing more information about which operation failed.

chore: improve error messages for Kind

---

third_party/helm/helm.go

This change captures stderr from helm commands. 
This changes the current behavior of returning `exit status 1` to now include the reason for the failure, ex:
```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists...
```

feat: Display helm command errors

---

klient/wait/conditions/conditions.go
klient/wait/wait_test.go

This PR adds a new condition to check if a deployment is available. The wait condition only requires the user to provide the deployment name and namespace and the condition method will handle building the deployment object/checking the deployment condition for a match.
With this new condition, it will remove the need for the user to build the deployment object and call deployment condition match condition in their code bases.
_Before_
```go
import (
"os"
appsv1 "k8s.io/api/apps/v1"
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
"sigs.k8s.io/e2e-framework/klient/wait"
"sigs.k8s.io/e2e-framework/klient/wait/conditions"
)
deployment := &appsv1.Deployment{ObjectMeta: metav1.ObjectMeta{Name: "deployment", Namespace: "namespace"}}
err = …
```

Add condition for checking if a deployment is available

---

.golangci.yml
examples/crds/main_test.go
examples/dry_run/main_test.go
examples/every_test_custom_ns/main_test.go
examples/flags/flags_test.go
examples/pod_exec/envtest_test.go
examples/real_cluster/main_test.go
examples/third_party_integration/helm/helm_test.go
examples/third_party_integration/helm/main_test.go
examples/watch_resources/watch_test.go
hack/verify-golangci-lint.sh

Enabling linters on the `example/**` components so that they can be linted alongside the other packages codes.
Along with that, this PR also bumps up the `golangci-lint` version and sets-up the `depguard` linter config for allowed packages under tests and main
Closes #280

enable linters of examples and update golangci-lint version

---

ADOPTERS.md

Adding file ADOPTERS.md and its first adopter.
Fixes #215

Adding file ADOPTERS.md

---

examples/table/table_test.go
pkg/env/env.go
pkg/features/builder.go
pkg/features/feature.go
pkg/features/table.go
pkg/internal/types/types.go

Enable Test Table Description capabilities
Closes #277

add description feature to test tables

---

examples/third_party_integration/flux/template/deployment.yaml
examples/third_party_integration/flux/template/namespace.yaml
examples/third_party_integration/flux/template/service.yaml

Hi, 
This is hello-world go application template, which will be referenced by flux Kustomization example in #255. This needs to merged first otherwise tests won't pass in corresponding PR. 
cc: @harshanarayana @vladimirvivien

Add templates for flux example

---

pkg/env/env.go

fixes https://github.com/kubernetes-sigs/e2e-framework/issues/289 by adding stacktrace

show stacktrace when panic in env.Setup

---

examples/crds/envtest_test.go
examples/dry_run/dry_run_test.go
examples/multi_cluster/deployment_test.go
examples/parallel_features/parallel_features_test.go
examples/pod_exec/envtest_test.go
examples/third_party_integration/helm/helm_test.go
hack/test-go.sh
pkg/env/env.go
pkg/env/env_test.go
pkg/env/main_test.go
pkg/internal/types/types.go

This is another approach to solve the same problem as https://github.com/kubernetes-sigs/e2e-framework/pull/265 and was developed with the help of @maruina.
Supersedes https://github.com/kubernetes-sigs/e2e-framework/pull/291 as I think is a better approach w.r.t. the one proposed there.
This patch reduces the number of accesses to the context in the testEnv to only the ones that are strictly necessary and that should be synchronous. So, testEnv still contains a ctx, but is only to be used as a starting point and won't be updated except after the setup and finish phase.
According to the following logic:
- If `Test` is used, the same logic of now applies. So the context is passed to all features being run sequentially and the most updated version is then returned to the caller.
- If …

Fix race condition when executing parallel tests, passing context down and back

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

enable issue and pr templates

---

klient/decoder/decoder.go
klient/decoder/decoder_test.go

/kind bug
Previously, if an object has no annotations, new annotations would be created and set as the label, and then overrides would be set on the labels.
```release-note
fixed an issue with MutateAnnotations when the object had no existing annotations
```

bugfix MutateAnnotations

---

pkg/envconf/config.go
pkg/envconf/config_test.go

/kind bug
Currently `envconf.RandomName()` return a string with an empty prefix when no prefix was provided even though the godoc states:
```
If prefix is omitted, the then entire name is random char.
```
This PR fixes it by checking if an empty prefix was provided.
```release-note
fixes `envconfg.RandomName() returning a string beginning with `-` when an empty prefix is provided
```
```docs
```

fix: fix RandomName's dash when no prefix provided

---

pkg/env/env.go

/kind bug
Set the valid return code after recovering from a panic under the setup handlers so that the test suite is marked as failed instead of being wrongly marked as successful.
Fixes #328
NA
```release-note
NONE
```
```docs
NONE
```

fixed broken exit code settings during panic recovery

---

klient/wait/conditions/conditions.go

/kind feature
Adds a `conditions` helper for a `DaemonSet` that asserts its pods are scheduled and ready.
```release-note
Added `conditions.DaemonSetReady`, a wait helper for determining a DaemonSet is ready.
```

Add conditions.DaemonSetReady

---

support/kind/kind.go
support/kwok/kwok.go

/kind bug
This PR fix the situation, when someone would like to create Kind cluster with options, but without `kindConfigFile` defined, i.e.
```golang
envfuncs.CreateClusterWithConfig(kind.NewProvider(), kindClusterName, "", kind.WithImage("kindest/node:v1.22.2")),
```
In this case, create procedure will fails with unpredictable behavior:
```shell
15:14 $ make e2e 
go test ./test/e2e/... --v 4
F0906 15:17:25.100154   88839 env.go:375] Setup failure: failed to create kind cluster: exit status 1 : exit status 1: ERROR: unknown command "kindest/node:v1.27.3" for "kind create cluster"
```
```release-note
```
```docs
```

Validate kindConfigFile while configuring Kind cluster

---

.github/dependabot.yml
.github/workflows/release.yml
go.mod
hack/verify-golangci-lint.sh
pkg/envconf/config.go

/kind cleanup
- Updates on golang / golangci-lint and dependabot
test-infra PR to update go: https://github.com/kubernetes/test-infra/pull/31251
NONE
```release-note
NONE
```
```docs
```

Updates on golang / golangci-lint and dependabot

---

pkg/envfuncs/provider_funcs.go

/kind bug 
/kind regression
Remove unnecessary call to `cfg.client.RestConfig` in `CreateClusterWithConfig` . The cfg.Client() function expects cfg.kubeconfig to be set before calling. This is raising panic. Also the cfg.Client().RESTConfig() returns a restconfig which is not used anywhere in that function. 
Fixes # https://github.com/kubernetes-sigs/e2e-framework/issues/369
```release-note
```
```docs
```

Resolve issue #369 by eliminating the redundant invocation of cfg.client.RestConfig in CreateClusterWithConfig, which is leading to a panic

---

klient/wait/wait.go
klient/wait/wait_test.go

/kind bug
Fixes #
``` golang
err = wait.For(
func(ctx context.Context) (done bool, err error) {
...
},
wait.WithContext(ctx),
wait.WithTimeout(600*time.Second),
)
```
The timeout is ignored when both context and timeout are specified
```release-note
NONE
```
```docs
NONE
```

Fix timeout with context for wait

---

pkg/features/builder.go
pkg/features/feature.go

/kind cleanup
[WithStep](https://github.com/kubernetes-sigs/e2e-framework/blob/15e91144243aab9c611f5706c3e7c48ceb881850/pkg/features/builder.go#L42) accepts a Level as argument, but the actual levels (Setup, Assess, Teardown)  are only declared in an internal package and not publicly exposed. This PR exposes the internal specific Levels.
Fixes https://github.com/kubernetes-sigs/e2e-framework/issues/288
Has to be said that any other Level w.r.t. the 3 intended ones will be ignored, as the code explicitly selects the three steps, so we could also go the other way, remove the public Level and avoid exposing WithStep and WithDescribeStep private, but that would be a breaking change unfortunately.
```release-note
```
```docs
```

refactor: expose Levels

---

docs/test-execution-order.md

/kind documentation
Short writeup to document the different execution steps of the e2e-framework
It helps answer question for https://github.com/kubernetes-sigs/e2e-framework/issues/366

Documentation that shows e2e-framework test execution order

---

pkg/envfuncs/main_test.go
pkg/envfuncs/ns_funcs.go
pkg/envfuncs/ns_funcs_test.go

/kind feature
Create 2 new option functions that can be used when calling `CreateNamespace` to add custom labels and annotations to the namespace.
Fixes #364 
I also added tests to make sure the function work as expected (this is how I discovered #381), however it looks like there is no automated testing in place. In the meantime, tests can be run with `go test ./pkg/envfuncs`.
To be merged after #381 
```release-note
Added a way to create namespaces with custom labels and annotations
```
```docs
```

Allow custom labels and annotations for namespace creation

---

OWNERS

/kind cleanup
- add cpanato as approver and move spiffxp to emeritus_approvers also order alphabetically
/assign @vladimirvivien @ShwethaKumbla @harshanarayana
Fixes #
```release-note
NONE
```
```docs
```

add cpanato as approver and move spiffxp to emeritus_approvers also order alphabetically

---

examples/graceful_setup_fail/main_test.go
pkg/env/env.go

When an error happens during a setup step, instead of calling `klog.Fatal` which causes `os.Exit`, instead do `klog.Error`, `break`, run `defer` function with clean up steps, and `return`.
/kind bug
I found [this line](https://github.com/kubernetes-sigs/e2e-framework/blob/d19e8b569fb2f94568f8ed74b00227f879798aa0/pkg/env/env.go#L369) to be the problem as to why our KinD cluster deletion was not happening as intended. As soon as an error value is passed during a setup step, `klog.Fatalf(...)` is called:
```go
for _, setup := range setups {
// context passed down to each setup
if e.ctx, err = setup.run(e.ctx, e.cfg); err != nil {
klog.Fatalf("%s failure: %s", setup.role, err)
}
}
```
According to [klog docs](https://github.com/kubernetes/klog/blob/6ded8085b27eeaf68a13d583a382b125ef1482ee/klog …

After setup error, do klog.Error not klog.Fatal, and move on

---

support/kind/kind.go

/kind bug
The current support E2EClusterProvider API for creating Kind clusters is confusing/misleading.
Say, I want to create a Kind cluster with a custom image:
```go
import "sigs.k8s.io/e2e-framework/support/kind"
p := kind.NewProvider().WithOpts(kind.WithImage("..."))
```
When used with `envfuncs.CreateCluster` I would expect this to work, but when you dig down to it, the image name is never passed down to the CLI arguments:
https://github.com/kubernetes-sigs/e2e-framework/blob/fdcf509f96c96f0055b03f026ea44c62df82c753/support/kind/kind.go#L170
Confusingly, the other variant `kind.CreateWithConfig` does https://github.com/kubernetes-sigs/e2e-framework/blob/fdcf509f96c96f0055b03f026ea44c62df82c753/support/kind/kind.go#L153
The behavior should be the same for both.

fix(support): propagate kind image options to CLI

---

pkg/env/env.go

/kind bug
When writing tests, this allows the writer to control whether the test should continue running the next assess when a failure occurs. Basically, they can chose between using `t.FailNow()` or `t.Fail()` depending on if the failure should stop the test or not. It works independently from the `-fail-fast` flag specific to the framework and allows a more granular control on test failures.
Fixes #386 
I tried to add a new test for this case but couldn't find a way to make it work. Since `failNow` is called, the test fails and I couldn't find a way to expect a test to fail in go :sweat_smile:. Happy to add one if someone has an idea on how to do it though.
You can use the following code to illustrate what I'm trying to solve
```go
package envfuncs_test
import (
"context"
"os" …
```

[env] Don't run next assess when failNow is called

---

support/kind/kind.go
support/kwok/kwok.go

/kind bug
ssia.
Currently, when a cluster already exists, `initKubernetesAccessClients` won't be run.
`initKubernetesAccessClients` is mandatory to be run to make `*cluster` return `KubernetesRestConfig`, and consequently now `KubernetesRestConfig` always results in `nil` in such case. 
Fixes #
```release-note
Fix a bug which both kwok and kind providers don't work expectedly when a cluster already exists.
```
```docs
```

initialize k8s client access appropriately when a cluster exists

---

klient/decoder/decoder.go

/kind bug
When decoding fails, the decoder has no knowledge about the filename, but `DecodeEachFile` has. The later should add it to the error context.
Fixes #
```release-note
NONE
```
```docs
```

klient/decoder: add filename context to decode error

---

pkg/env/env.go
pkg/env/env_test.go

/kind bug
In case multiple `BeforeEachTest` or `AfterEachTest` actions are used, the values of the context created by the first registered action are not propagated further.
N/A
If the modified unit test would be run without the bug fix the output would be:
```
--- FAIL: TestEnv_Test (0.00s)
--- FAIL: TestEnv_Test/context_value_propagation_with_with_multiple_features,_before,_during,_and_after_test (0.00s)
env_test.go:643: Expected:
[before-each-test-1 before-each-test-2 test-feat-1 test-feat-2 after-each-test-1 after-each-test-2] but got result:
[before-each-test-2 test-feat-1 test-feat-2 after-each-test-2]
FAIL
FAIL    sigs.k8s.io/e2e-framework/pkg/env       8.020s
FAIL
```
```release-note
```

Fix value propagation in context for test actions

---

examples/third_party_integration/README.md
examples/third_party_integration/ko/ko_test.go
examples/third_party_integration/ko/main_test.go
examples/third_party_integration/ko/testdata/example_goapp/main.go
third_party/helm/helm.go
third_party/ko/ko.go

Add Install, BuildLocal and GetLocalImage functions.
/kind feature
Already explained in #343 
Partially addresses #343 
N/A
```release-note
NONE
```
```docs
N/A
```

third_party/ko: Add ko as third party tools

---

pkg/env/env.go

/kind bug
Since the last changes ( #362) in the error handling of the setup functions, the test suite is also executed if the setup has failed. This can cause the tests to run to timeout because the expected prerequisites are not met. This PR introduces a check to ensure that the test suite is only executed if the setup was successful, otherwise the function returns with exit code 1 and the finish functions are gracefully executed.
Fixes #423
None
```docs
The test suite is only executed if the setup was successful.
```
```docs
```

execute test suite only if the setup was successful

---

pkg/env/env.go
pkg/env/env_test.go
pkg/envconf/config.go

/kind feature
Following discussions in https://github.com/kubernetes-sigs/e2e-framework/pull/367
This PR fixes a bug where the config object was shared between tests. When running tests in parallel, it was then impossible to rely on fields like the namespace because they could have been overwritten by another test. Also, it led to tests using `-race` to fail because the shared config.klient object that were updating the same fields when initializing the client.
This PR creates a new `deepCopyConfig` method that allows to create a deep copy of the config object. This way, each test can have its own without impacting the others. Now the config has the following lifecycle:
- It is created when a testEnv is created
- Each test uses a child testEnv that inherits the main testEnv's config
- …

[env] Do not share config between tests

---

pkg/env/action.go
pkg/env/env.go

/kind feature
In Crossplane we try to use reusable step functions in our E2E tests, so they end up looking like this:
```go
func TestExample(t *testing.T) {
environment.Test(t,
features.New(t.Name()).
WithSetup("ExampleSetup", funcs.SomeSetupFn()).
Assess("ExampleAssess", funcs.SomeAssessFn()).
WithTeardown("ExampleTeardown", funcs.SomeTearDownFn()).
Feature(),
)
}
```
Since step functions are passed `*testing.T` we'll often call `t.Error`, `t.Log`, etc from our step functions. These testing calls include the call point (i.e. filename and line number) in their output. Without using `t.Helper()` the call point will be the file where the step function is defined (e.g. `features.go`) rather than the calling test.
We want to mark our step functions as test helpers using `t.Helper` so that the …

Mark E2E plumbing as test helpers

---

examples/multi_cluster/deployment_test.go
examples/pod_exec/envtest_test.go

/kind cleanup
- add teardown when TestExecPod finished
Fixes #
None
```release-note
None
```
```docs
None
```

add teardown when TestExecPod finished

---

pkg/env/env.go
pkg/types/types.go

/kind feature
This pull request adds a function to the `types.Environment` kind that allows access of the environment configuration used by the test environment. This may allow for ad-hoc uses cases not supported by the test suite, such as: https://github.com/kubernetes-sigs/e2e-framework/issues/268 
Fixes #
```release-note
NA
```
```docs
NA
```

feat: allow accessing the test environments env config

---

examples/vcluster/vcluster_with_config/main_test.go
examples/vcluster/vcluster_with_config/values.yaml
go.mod
pkg/env/env.go
third_party/flux/flux_setup.go
third_party/helm/helm.go
third_party/ko/ko.go
third_party/kubetest2/pkg/tester/e2e-tester_test.go
third_party/vcluster/vcluster.go
third_party/vcluster/vcluster_test.go

addition of vcluster provider; interested to see if the CI fails. vcluster needs a "host" cluster to launch into, so I've followed an existing example where a real cluster or kind cluster are utilized as necessary: https://github.com/kubernetes-sigs/e2e-framework/blob/9206e6f6082907a1c77750b7cac0fc44ff4dac02/examples/real_cluster/main_test.go#L39
/kind feature
This PR enables a new `E2EClusterProvider` for `vcluster` based clusters.
Fixes #
```release-note
NONE
```
```docs
NA
```

feat: add vcluster e2e cluster provider

---

README.md

/kind documentation
Fixes the README.md `TestMain` example which was using a deprecated API and removing a namespace that did not exist.
NONE
```release-note
NONE
```
```docs
- [Other doc]: https://github.com/kubernetes-sigs/e2e-framework/blob/main/README.md
```

docs: fix README.md TestMain example

---

support/kwok/kwok.go
third_party/kwok/kwok.go

/kind feature
This allows `kwok` clusters to be created with a custom wait time option.
Fixes #478
I wasn't sure if it was better to have a receiver method on `*Cluster` or use the `ClusterOptions`. I couldn't find a concrete usage example of the Cluster Options for `kwok` anywhere, but thought it to be the least impactful change to allow this feature to be set. This is my first PR to the e2e-framework, so any feedback is appreciated!
```release-note
NONE
```

Add `WithWaitDuration` ClusterOpts function

---

klient/decoder/decoder.go
klient/decoder/decoder_test.go

Fixes #474 
```release-note
"NONE"
```
```docs
DecodeURL is a stream of documents from the URL of any Kind using either the innate typing of the scheme.
Falls back to the unstructured.Unstructured type if a matching type cannot be found for the Kind.
```

Add specific DecodeURL function in decoder package

---

pkg/types/types.go
third_party/k3d/k3d.go
third_party/kind/kind.go
third_party/kwok/kwok.go
third_party/vcluster/vcluster.go

/kind feature
When dealing with multi-cluster setup we ran into issue where we need to pass arguments into `GetKubeconfig` method. 
Specific example in our case was `--internal` to `kind` so cluster can speak to different clusters.
This extends this so you can do things like:
```
internalKubeConfigOpts := kind.WithGetKubeConfigArgs("--internal")
internalKubeConfig, err := kindEdgeCluster.WithOpts(internalKubeConfigOpts).GetLiveKubeconfig()
if err != nil {
log.Printf("Failed to get edge cluster kubeconfig: %s", err)
return ctx, err
}
installCmd := fmt.Sprintf(
`bash -c "KUBECONFIG=%s kubectl create secret generic edge-cluster-kubeconfig -n omni-operator-system  --from-file=kubeconfig=%s"`,
kindMasterCluster.GetKubeconfig(),
internalKubeConfig,
)
```
Or similar pattern if you want to set …

Extend GetKubeconfig methods with args

---

pkg/env/env.go

/kind bug
Fixes a regression introduced in https://github.com/kubernetes-sigs/e2e-framework/pull/334 when skipping a single feature inside a `testEnv.Run` call, all other features get skipped due to how the `t.Skip` was moved out of the per-feature execution test scope to address a separate concern with feature before/after steps.
This PR makes the entire feature processing call part of single test scope, that way feature skipping does not cause noise to neighbors.
Fixes #
```release-note
N/A
```
```docs
N/A
```

fix: make test scope per-feature
