kubernetes-sigs/e2e-framework

pkg/env/env_test.go
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>
=> add testenv unit tests passing context values

docs/design/klient-package.md, klient/k8s/object.go, klient/k8s/resources/resources.go, klient/k8s/resources/resources_test.go
This PR adds additional helper methods to handle k8s objects.
=> helper functions for handling k8s objects

examples/k8s/kindsupport.go, klient/conf/main_test.go, klient/k8s/resources/main_test.go, klient/k8s/resources/resources.go, klient/k8s/resources/resources_test.go, pkg/envsupport/support.go, support/kind/kind.go
This PR introduces support helper for kind cluster creation.
=> add support functionality for kind

README.md
* Clarify the language describing the project
* Also added small code snippet of example
=> Update to the root README file

examples/kind/kind_with_config/kind-config.yaml, examples/kind/kind_with_config/kind_with_config_test.go, examples/kind/kind_with_config/main_test.go, pkg/envfuncs/kind_funcs.go, support/kind/kind.go
- Add a new function to be able to create a KinD cluster with image and config
- Add a new testing file for the new cluster with Config (Image and kind-config.yaml)
Fixes: #72
=> feat: Kind Cluster with Config

docs/design/test-harness-framework.md
Fix typos in the design document.
=> Fix typos in the design document

support/kind/kind.go
If a cluster is already created when Create/CreateWithConfig is called, the kubeconfig is not returned -- I think that may be unexpected to the code that calls this:
https://github.com/kubernetes-sigs/e2e-framework/blob/84123945caf59b33f30ce1cd8f1d9e01a0d3c93b/pkg/envfuncs/kind_funcs.go#L41-L50
Fixing this helped resolve this panic when I try to re-use a cluster to save some time between testing packages:
```
panic: envconfig: client failed: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
goroutine 1 [running]:
sigs.k8s.io/e2e-framework/pkg/envconf.(*Config).Client(0xc000112060)
/path/to/code/vendor/sigs.k8s.io/e2e-framework/pkg/envconf/config.go:127 +0xcb
github.com/org/repo/mypkg.Main.func1({0x24381a0, 0xc0001322d0}, …
```
=> Allow re-use of kind clusters

examples/flags/README.md, examples/flags/flags_test.go, examples/kind/kind_with_config/kind_with_config_test.go, examples/kind/kind_with_config/main_test.go, examples/skip_flags/main_test.go, examples/sonobuoy/k8s_test.go, examples/suites/main_test.go, go.mod, klient/conf/main_test.go, klient/internal/testutil/setup.go, klient/k8s/resources/main_test.go, klient/k8s/resources/resources.go, klient/k8s/resources/resources_test.go, klient/wait/conditions/conditions.go, klient/wait/main_test.go, klient/wait/wait_test.go, pkg/env/env.go, pkg/env/main_test.go, pkg/envconf/config.go, pkg/flags/flags.go, support/kind/kind.go
=> GIT-77: enable klog based generic logging infra with verbose handlers

docs/design/klient-package.md
=> GIT-81: fix syntax highlighting for klient Design Doc

.gitignore, examples/table/README.md, examples/table/table_test.go, pkg/env/env.go, pkg/features/table.go
This patch introduces support for table-driven tests using the framework.
Fixes #89
=> Support for table-driven test representation

support/kind/kind.go
The current implementation of how we check for cluster existence is too permissive:
https://github.com/kubernetes-sigs/e2e-framework/blob/fee1391aeccdc260069bd5e0b25c6b187c2293c4/support/kind/kind.go#L87-L90
If clusters are created using a similar prefix or using a name that happens to be a substring of another cluster, this will not work as intended.
Adjusted the function signature slightly, in the attempt to reduce code duplication. _Most_ users should be unaffected as the addition is a variadic parameter:
```go
func (k *Cluster) CreateWithConfig(imageName, kindConfigFile string) (string, error) {
return k.Create("--image", imageName, "--config", kindConfigFile)
}
func (k *Cluster) Create(args ...string) (string, error) {
...
```
=> match on exact cluster names

examples/parallel_features/README.md, examples/parallel_features/parallel_features_test.go, examples/table/table_test.go, pkg/env/env.go, pkg/env/env_test.go, pkg/envconf/config.go, pkg/envconf/config_test.go, pkg/flags/flags.go, pkg/flags/flags_test.go, pkg/internal/types/types.go
=> GIT-49: enable parallel run of test features

Makefile, examples/third_party_integration/README.md, examples/third_party_integration/helm/README.md, examples/third_party_integration/helm/helm_test.go, examples/third_party_integration/helm/main_test.go, examples/third_party_integration/helm/testdata/example_chart/.helmignore, examples/third_party_integration/helm/testdata/example_chart/Chart.yaml, examples/third_party_integration/helm/testdata/example_chart/templates/deployment.yaml, examples/third_party_integration/helm/testdata/example_chart/templates/service.yaml, examples/third_party_integration/helm/testdata/example_chart/templates/tests/test-connection.yaml, examples/third_party_integration/helm/testdata/example_chart/values.yaml, hack/install-helm.sh, third_party/helm/helm.go
=> GIT-83: enable helm support for test workflow

hack/verify-boilerplate.sh, hack/verify-golangci-lint.sh
- update repo infra to release v0.2.5
- update golangci-lint to v1.44.0
/assign @vladimirvivien
=> updates on golangci-lint and repo-infra

.github/workflows/release.yml, .gitignore, .goreleaser.yml
Fixes: #113 
rehearsal on my fork: https://github.com/cpanato/e2e-framework/runs/5220056082?check_suite_focus=true
release: https://github.com/cpanato/e2e-framework/releases/tag/v99.99.01
/assign @vladimirvivien
=> add github actions/goreleaser to release the lib

pkg/features/builder.go, pkg/features/builder_test.go
=> GIT-94: enable extended Feature API to provide named setup and teardown

docs/design/k8s-resource-watcher.md, docs/design/test-harness-framework.md, examples/watch_resources/README.md, examples/watch_resources/main_test.go, examples/watch_resources/watch_test.go, klient/decoder/decoder.go, klient/k8s/resources/resources.go, klient/k8s/watcher/watch.go
This PR provides an implementation for #97.
=> implement k8s resource watch and trigger action based on the events

README.md
Fix function call errors in README
=> Fix function call errors in README

examples/watch_resources/watch_test.go
This PR is part of https://github.com/kubernetes-sigs/e2e-framework/pull/125#discussion_r886177445
=> additional test case to validate watch functionality

docs/design/klient-package.md, docs/design/resource-decoding.md, docs/design/test-harness-framework.md
Miscellaneous fixes, all minor.
=> docs: Fix some typos and code examples

.gitignore, examples/pod_exec/README.md, examples/pod_exec/envtest_test.go, examples/pod_exec/main_test.go, examples/wait_for_resources/wait_test.go, go.mod, go.sum, klient/k8s/resources/resources.go, klient/k8s/resources/resources_test.go
Hi,
The original PR is here:
https://github.com/kubernetes-sigs/e2e-framework/pull/163
I needed to reopen this one as I was cleaning git history.
Thanks
=> Add ExecInPod method with an example test

support/kind/kind.go
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
=> bump kind to 0.17

.github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
closes #164
Signed-off-by: jbpratt <jbpratt78@gmail.com>
=> enable dependabot scheduled updates

OWNERS
This PR is to add @harshanarayana to the list of reviewers and approvers.
If you look at the history of commits for this project, you will see that Harsha is the second highest number of contribution to this project. 
cc @cpanato @ShwethaKumbla
=> Adding harshanarayana as review/approver

klient/wait/conditions/conditions.go
Adds logging to `conditions.ResourcesDeleted` like with `conditions.ResourceDeleted`
=> feat: add logging for conditions.ResourcesDeleted

pkg/env/env.go
=> feat: add env.TestFunc type alias

klient/k8s/resources/resources.go
Fixes #254
**NOTE:**
I have made the changes to all the options used by this resources handler since they can all run into similar issues as reported in #254
=> handle conversion of resource handler options properly between metav1 and controller-runtime

support/kind/kind.go, third_party/helm/helm.go
=> enable using kind/helm binaries from non standard location

support/kind/kind.go
Closes #282 
Earlier PR #286 was not entirely done but got merged a bit too early. :)
=> enable using kind binary from non standard location

support/kind/kind.go
=> fix: CreateWithConfig handling empty image

examples/kwok/kwok_with_config/kwok_test.go
=> Increase timeout for kwok test to make it stable

examples/third_party_integration/flux/README.md, examples/third_party_integration/flux/kyverno/flux_test.go, examples/third_party_integration/flux/kyverno/kyverno-values.yaml, examples/third_party_integration/flux/kyverno/main_test.go, examples/third_party_integration/flux/nginx/flux_test.go, examples/third_party_integration/flux/nginx/main_test.go, third_party/flux/cmd_manager.go, third_party/flux/flux_setup.go
/kind feature
Hello again,
This time I would like to extend flux functionality and add support for HelmRepository and HelmRelease objects. There is a simple kyverno example of how to use these objects.
Docs provided in README file.
=> Add flux HelmRepository and HelmRelease support with example

support/kwok/kwok.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> support/kwok: Print process output due to an error

support/kind/kind.go, support/kwok/kwok.go
/kind cleanup
Clean the rest like #349
Fixes #
```release-note
NONE
```
```docs
NONE
```
=> Print the complete error when fails

pkg/envfuncs/ns_funcs.go
/kind bug
The function DeleteNamespace was not succeeding in retrieving the namespace from the context because it tried to cast a corev1.Namespace to *corev1.Namespace.
Fixes #
```release-note
```
```docs
```
=> Fix DeleteNamespace not retrieving ns from ctx

klient/decoder/decoder.go, klient/decoder/decoder_test.go, klient/decoder/testdata/example-multidoc-emptyitemcomment.yaml
/kind bug
Changes in this PR enable adding empty yaml document that starts with just plain Comments while using the `decoder` package. eg. Is the one under https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/experimental-install.yaml . 
Fixes #388
NA
```release-note
NA
```
```docs
```
=> bugfix: skip empty document with just comments while using decoder pkg

support/kind/kind.go, support/utils/command.go
/kind bug
The current kubeconfig is created with both stdout and stderr. We should only use stdout to create the kubeconfig.
Fixes #347 
```release-note
NONE
```
```docs
NONE
```
=> support/kind: create kubeconfig with stdout
